seniors-project/backend

.github/workflows/cr.yml

Pull Request 주최자 변경
환경설정에서 사용하는 TOKEN을 GITHUB_TOKEN으로 변경
env에 변경된 TOKEN을 확인해주세요
- 특이사항1
- 특이사항2

Edit PR token

---

.github/workflows/gradle.yml
Dockerfile
src/main/java/com/seniors/example/example.java

- Github Actions workflow 작성
- Dockerfile 작성
- 연습용 exercise controller 생성
- 특이사항1
- 특이사항2

Github Workflow 및 Dockerfile 생성

---

.github/workflows/gradle.yml

Docs : workflow에 develop 브랜치 추가

---

src/test/java/com/seniors/domain/post/controller/PostControllerTest.java
src/test/java/com/seniors/domain/post/service/PostServiceTest.java

Test : 게시글 테스트 코드 수정 #25

---

Dockerfile
src/main/java/com/seniors/example/example.java

Docs : Dockerfile copy 경로 수정 #21

---

src/main/java/com/seniors/example/example.java

테스트할 문자열 수정 #21

---

.github/workflows/gradle.yml

Github Actions workflow 수정 #21

---

build.gradle
src/main/java/com/seniors/common/annotation/LoginUsers.java
src/main/java/com/seniors/common/constant/ResultCode.java
src/main/java/com/seniors/common/dto/ErrorResponse.java
src/main/java/com/seniors/common/exception/ExceptionHandlerFilter.java
src/main/java/com/seniors/common/exception/type/SignInException.java
src/main/java/com/seniors/config/ClientConfig.java
src/main/java/com/seniors/config/WebMvcConfig.java
src/main/java/com/seniors/config/resolver/LoginUserDetailsResolver.java
src/main/java/com/seniors/config/security/CustomUserDetails.java
src/main/java/com/seniors/config/security/JwtUtil.java
src/main/java/com/seniors/config/security/SecurityConfig.java
src/main/java/com/seniors/config/security/SecurityService.java
src/main/java/com/seniors/config/security/TokenFilter.java
src/main/java/com/seniors/config/security/TokenService.java
src/main/java/com/seniors/domain/auth/common/AuthTokensGenerator.java
src/main/java/com/seniors/domain/auth/common/OAuthInfoResponse.java
src/main/java/com/seniors/domain/auth/dto/AuthTokens.java
src/main/java/com/seniors/domain/auth/kakao/KakaoApiClient.java
src/main/java/com/seniors/domain/auth/kakao/KakaoInfoResponse.java
src/main/java/com/seniors/domain/auth/service/OAuthLoginService.java
src/main/java/com/seniors/domain/post/controller/PostController.java
src/main/java/com/seniors/domain/post/dto/PostDto.java
src/main/java/com/seniors/domain/post/entity/Post.java
src/main/java/com/seniors/domain/post/repository/PostRepositoryCustom.java
src/main/java/com/seniors/domain/post/repository/PostRepositoryImpl.java
src/main/java/com/seniors/domain/post/service/PostService.java
src/main/java/com/seniors/domain/users/entity/Users.java

카카오 로그인 및 회원가입 구현
카카오 애플리케이션에서 발급받은 Client-id와 CallbackUrl를 활용하여
Client가 요청한 CallbackUrl로 발급받은 authorizationCode로 유저 정보를 response 받아
그에 맞는 AccessToken을 생성하여 response 해준다.
- CustomUserDetail로 userId를 들고 오도록 구현 
- jjwt 0.11.5 버전부터는 Deprecated된 기능들이 많아 리팩토링하여 새롭게 개발

카카오 로그인 및 회원가입 구현

---

build.gradle
src/main/java/com/seniors/example/example.java
src/main/resources/logback-spring.xml

Log를 slack으로 알림 보내는 기능 구현

---

build.gradle
src/main/java/com/seniors/config/WebSocketConfig.java
src/main/java/com/seniors/domain/chat/dto/ChatMessageDto.java
src/main/java/com/seniors/domain/chat/dto/ChatRoomDto.java
src/main/java/com/seniors/domain/chat/entity/ChatMessage.java
src/main/java/com/seniors/domain/chat/entity/ChatRoom.java
src/main/java/com/seniors/domain/chat/entity/ChatRoomMembers.java
src/main/java/com/seniors/domain/users/entity/Users.java

엔티티, DTO 생성 및 환경설정
채팅방과 관련한 엔티티 및 DTO 생성, 웹 소켓 환경설정
- 기존 형식에 맞게 잘 생성되었는지 확인해주시면 감사하겠습니다 :)

ChatMessage, ChatRoom 엔티티 생성 및 매핑, 웹 소켓 환경설정

---

src/main/java/com/seniors/common/constant/ResultCode.java
src/main/java/com/seniors/config/DataSourceConfig.java
src/main/java/com/seniors/domain/comment/entity/Comment.java
src/main/java/com/seniors/domain/post/controller/PostController.java
src/main/java/com/seniors/domain/post/entity/Post.java
src/main/java/com/seniors/domain/post/repository/PostRepositoryCustom.java
src/main/java/com/seniors/domain/post/repository/PostRepositoryImpl.java
src/main/java/com/seniors/domain/post/service/PostService.java
src/main/java/com/seniors/domain/users/controller/UsersController.java
src/test/java/com/seniors/domain/post/service/PostServiceTest.java

User 검증 API 및 ResultCode 코드 값 변경
사용자 검증을 위한 API 개발로 userDetails로 null값인지 조건 추가하여 개발

User 검증 API 및 ResultCode 코드 값 변경

---

src/main/java/com/seniors/domain/resume/controller/ResumeController.java

>DataResponse의 제네릭 타입을 swagger에서 인식 못함
>제네릭 대신 직접 DTO 대입

swagger 어노테이션 변경 #49

---

src/main/java/com/seniors/common/dto/CustomSlice.java
src/main/java/com/seniors/common/exception/ExceptionControllerAdvice.java
src/main/java/com/seniors/common/exception/ExceptionRestControllerAdvice.java
src/main/java/com/seniors/domain/resume/controller/ResumeController.java
src/main/java/com/seniors/domain/resume/dto/CareerDto.java
src/main/java/com/seniors/domain/resume/dto/CertificateDto.java
src/main/java/com/seniors/domain/resume/dto/EducationDto.java
src/main/java/com/seniors/domain/resume/dto/ResumeDto.java
src/main/java/com/seniors/domain/resume/entity/Career.java
src/main/java/com/seniors/domain/resume/entity/Certificate.java
src/main/java/com/seniors/domain/resume/entity/Education.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java
src/test/java/com/seniors/domain/resume/controller/ResumeControllerTest.java
src/test/java/com/seniors/domain/resume/repository/ResumeRepositoryTest.java
src/test/java/com/seniors/domain/resume/service/ResumeServiceTest.java

이력서 도메인 api 리팩토링

---

src/main/java/com/seniors/domain/chat/controller/ChatRoomController.java
src/main/java/com/seniors/domain/chat/dto/ChatMessageDto.java
src/main/java/com/seniors/domain/chat/dto/ChatRoomDto.java
src/main/java/com/seniors/domain/chat/dto/ChatRoomMembersDto.java
src/main/java/com/seniors/domain/chat/entity/ChatMessage.java
src/main/java/com/seniors/domain/chat/entity/ChatRoom.java
src/main/java/com/seniors/domain/chat/entity/ChatRoomMembers.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepository.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepositoryCustom.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepositoryImpl.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomRepositoryCustom.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomRepositoryImpl.java
src/main/java/com/seniors/domain/chat/service/ChatRoomService.java
src/main/java/com/seniors/domain/users/dto/UsersDto.java
src/main/java/com/seniors/domain/users/repository/UsersRepositoryCustom.java
src/main/java/com/seniors/domain/users/repository/UsersRepositoryImpl.java

채팅방 조회 API 리팩토링 및 기능 추가 
- 전체 채팅방 조회시 Pagenation을 사용하지 않고 List형태로 반환합니다.

채팅방 조회 API 리팩토링 및 기능 추가 #56

---

src/main/java/com/seniors/common/constant/ResultCode.java
src/main/java/com/seniors/common/exception/ExceptionControllerAdvice.java
src/main/java/com/seniors/common/exception/type/ForbiddenException.java
src/main/java/com/seniors/domain/auth/controller/AuthController.java
src/main/java/com/seniors/domain/chat/controller/ChatMessageController.java
src/main/java/com/seniors/domain/chat/controller/ChatRoomController.java
src/main/java/com/seniors/domain/comment/controller/CommentController.java
src/main/java/com/seniors/domain/notification/controller/NotificationController.java
src/main/java/com/seniors/domain/notification/service/NotificationService.java
src/main/java/com/seniors/domain/post/controller/PostController.java
src/main/java/com/seniors/domain/post/service/PostService.java
src/main/java/com/seniors/domain/resume/controller/ResumeController.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java
src/main/java/com/seniors/domain/users/controller/UsersController.java

Controller 단 Swagger 수정 #68
Swagger 에러 Response 내용 수정 및 추가 (statusCode 401, 404, 500)
- 특이사항1
- 특이사항2

Controller 단 Swagger 수정 #68

---

src/main/java/com/seniors/config/DataSourceConfig.java

채팅방 조회 쿼리 수정 #69
DataSourceConfig 주석제거
- 특이사항1
- 특이사항2

채팅방 조회 쿼리 수정 #69

---

src/main/java/com/seniors/domain/resume/controller/ResumeController.java
src/main/java/com/seniors/domain/resume/repository/ResumeRepository.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java

Refactor : 이력서 도메인 api 리팩토링

---

src/main/java/com/seniors/config/DataSourceConfig.java
src/main/java/com/seniors/config/JpaConfig.java

DB 이중화 작업 해제

---

src/main/java/com/seniors/domain/resume/entity/Resume.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java

기본 이미지 처리 리팩토링

---

.github/workflows/build.yml
.github/workflows/deploy.yml
deploy.sh

기존 : develop에 push 시 빌드, 배포 전부 수행 
변경 : develop에 push 시 빌드만, main에 push 시 배포 수행

CICD 코드 관련 리팩토링

---

src/main/java/com/seniors/domain/chat/controller/ChatRoomController.java
src/main/java/com/seniors/domain/chat/dto/ChatRoomMembersDto.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepository.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepositoryCustom.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepositoryImpl.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomRepositoryImpl.java
src/main/java/com/seniors/domain/chat/service/ChatRoomService.java

채팅방 도메인 api 리팩토링
- 특이사항1
- 특이사항2

채팅방 도메인 api 리팩토링

---

build.gradle
src/main/resources/logback-spring.xml

sentry 관련 코드 추가

---

.github/workflows/build.yml
.github/workflows/deploy.yml

github actions workflow 수정 for k8s

---

Dockerfile

Setting : Dockerfile 수정 #86

---

.github/workflows/deploy.yml

Github actions workflow 수정

---

.github/workflows/build.yml
.github/workflows/deploy.yml
deploy.sh

github actions workflow 수정 #86

---

.github/workflows/build.yml
.github/workflows/deploy.yml

github actions workflow 수정 

---

src/main/java/com/seniors/config/WebSocketConfig.java
src/main/java/com/seniors/domain/chat/controller/ChatMessageController.java
src/main/java/com/seniors/domain/chat/controller/ChatRoomController.java
src/main/java/com/seniors/domain/chat/service/ChatMessageService.java

채팅 도메인 api 리팩토링
> 채팅 도메인 api 리팩토링
- 특이사항1
- 특이사항2

Refactor : 채팅 도메인 api 리팩토링 #83

---

src/main/java/com/seniors/domain/resume/controller/ResumeController.java
src/main/java/com/seniors/domain/resume/dto/ResumeDto.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java
src/test/java/com/seniors/domain/resume/service/ResumeServiceTest.java

블로그 한번 참고해주시면 감사하겠습니다.
> 참고한 블로그 : https://leeggmin.tistory.com/7

이미지 + json 처리 방식 변경

---

.github/workflows/deploy.yml

> config repo를 private repository에서 organization으로 옮김
- 특이사항1
- 특이사항2

config repo를 organization에 옮김 

---

src/main/java/com/seniors/config/StompHandler.java

StompHandler 수정 #104

---

src/main/java/com/seniors/domain/chat/controller/ChatRoomController.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomMembersRepositoryImpl.java
src/main/java/com/seniors/domain/chat/repository/ChatRoomRepositoryImpl.java
src/main/java/com/seniors/domain/chat/service/ChatRoomService.java

채팅API 오류 수정 및 리팩토링

---

src/main/java/com/seniors/config/S3Uploader.java
src/main/java/com/seniors/domain/post/controller/PostController.java
src/main/java/com/seniors/domain/post/dto/PostDto.java
src/main/java/com/seniors/domain/post/service/PostService.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java
src/test/java/com/seniors/domain/post/controller/PostControllerTest.java
src/test/java/com/seniors/domain/post/service/PostServiceTest.java

Post 이미지 및 예외처리 개선
- S3Uploader 내 UUID 붙인 이유는 코드 바로 위 주석에 설명 작성함
- PostControllerTest에서 생성, 수정 API에 post나 patch 사용을 하되 multipart File이 업로드 안되서 multipart로 변경하여 수정

Post 이미지 및 예외처리 개선

---

src/main/java/com/seniors/domain/resume/dto/ResumeDto.java
src/main/java/com/seniors/domain/users/controller/UsersController.java
src/main/java/com/seniors/domain/users/dto/UsersDto.java
src/main/java/com/seniors/domain/users/entity/Users.java
src/main/java/com/seniors/domain/users/repository/UsersRepositoryCustom.java
src/main/java/com/seniors/domain/users/repository/UsersRepositoryImpl.java
src/main/java/com/seniors/domain/users/service/UsersService.java

Users 도메인에 대한 내 정보 조회, 수정 API 개발

Users 도메인에 대한 내 정보 조회, 수정 API 개발

---

src/main/java/com/seniors/domain/notification/controller/NotificationController.java
src/main/java/com/seniors/domain/notification/dto/NotificationDto.java
src/main/java/com/seniors/domain/notification/entity/Notification.java
src/main/java/com/seniors/domain/notification/repository/NotificationRepositoryImpl.java
src/main/java/com/seniors/domain/notification/service/NotificationService.java
src/main/java/com/seniors/domain/users/entity/Users.java

알림 단건 조회 및 알림 리스트 조회 권한 미체크 이슈

알림 단건 조회 및 알림 리스트 조회 권한 미체크 이슈 #121

---

src/main/java/com/seniors/domain/comment/controller/CommentController.java
src/main/java/com/seniors/domain/notification/controller/NotificationController.java
src/main/java/com/seniors/domain/post/controller/PostController.java
src/main/java/com/seniors/domain/resume/dto/ResumeDto.java
src/main/java/com/seniors/domain/resume/service/ResumeService.java
src/main/java/com/seniors/domain/users/controller/UsersController.java
src/test/java/com/seniors/domain/resume/controller/ResumeControllerTest.java
src/test/java/com/seniors/domain/resume/repository/ResumeRepositoryTest.java
src/test/java/com/seniors/domain/resume/service/ResumeServiceTest.java

Resume 도메인 리팩토링

---

.github/workflows/GithubActions.yaml

Refactor : github ations workflow 수정 #127

---

.github/workflows/GithubActions.yaml

Refactor : github actions workflow 수정 #127

---

src/test/java/com/seniors/domain/chat/controller/ChatMessageControllerTest.java
src/test/java/com/seniors/domain/chat/controller/ChatRoomControllerTest.java
src/test/java/com/seniors/domain/chat/service/ChatMessageServiceTest.java
src/test/java/com/seniors/domain/chat/service/ChatRoomServiceTest.java
src/test/java/com/seniors/domain/config/WithMockCustomUser.java
src/test/java/com/seniors/domain/config/WithMockCustomUserSecurityContextFactory.java

채팅 도메인 테스트 코드 작성 #117
